---

# Listen address, either with ip and port, or in case of
# port alone, prefix it with a ":", like ":8000"
http:
  cors:
    host: http://localhost:8888
  listen: 8888
  logfile: access.log

# Various timeout configuration options. The values are
# in seconds.
  timeout:
    idle: 10
    read: 10
    write: 30

database:
  # hostname: 192.168.101.4
  hostname: localhost
  port: 27017
  
  username: 
  password: 
  dbname: mongo-golang-test

tokenstore:
  hostname: localhost
  port: 6379
  username:
  password:
  dbname: 0
  protocol: 3

logging:
  level: info

tracing:
  enabled: false
  appname: my-application-name
  endpoint: localhost:4318

# Some dummy config
pizza:
  konijn: pizza
