// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package model

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthenticateRequest Authenticate
type AuthenticateRequest struct {
	Password string `json:"password" validate:"required,min=6,max=256"`
	Username string `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// AuthenticateToken Authenticate
type AuthenticateToken struct {
	Token string `json:"token" validate:"required"`
}

// Error Default error response
type Error struct {
	Error string `json:"error"`
	Logid string `json:"logid"`
}

// MetricsGetResponse Metrics for Prometheus response
type MetricsGetResponse = string

// Organisation The model Organisation object
type Organisation struct {
	Admins      []string  `json:"admins"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description" validate:"required,min=1,max=256"`
	Enabled     bool      `json:"enabled"`
	Fqdn        string    `json:"fqdn"`
	Id          string    `json:"id,omitempty"`
	Name        string    `json:"name" validate:"required,min=6,max=64,alphanum"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// OrganisationIn Input to create the Organisation object
type OrganisationIn struct {
	Admins      []string `json:"admins"`
	Description string   `json:"description" validate:"required,min=1,max=256"`
	Enabled     bool     `json:"enabled"`
	Fqdn        string   `json:"fqdn" validate:"required,fqdn"`
	Name        string   `json:"name" validate:"required,min=6,max=64,alphanum"`
}

// Organisations Overview of all organisations
type Organisations = []Organisation

// User The model User object
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Enabled   bool      `json:"enabled"`
	Id        string    `json:"id,omitempty"`
	OrgId     string    `json:"org_id" validate:"required"`
	Password  string    `json:"password" validate:"required,min=6,max=256,validatePassword"`
	Role      string    `json:"role" validate:"oneof=admin write readonly"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// UserIn Input to create the User object
type UserIn struct {
	Enabled  bool   `json:"enabled"`
	OrgId    string `json:"org_id" validate:"required"`
	Password string `json:"password" validate:"required,min=6,max=256"`
	Role     string `json:"role,omitempty" validate:"oneof=admin write readonly"`
	Username string `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// UserNoPassword Return of the User object
type UserNoPassword struct {
	CreatedAt time.Time `json:"created_at"`
	Enabled   bool      `json:"enabled"`
	Id        string    `json:"id" validate:"required"`
	OrgId     string    `json:"org_id" validate:"required"`
	Role      string    `json:"role" validate:"oneof=admin write readonly"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// GetAllOrganisationsParams defines parameters for GetAllOrganisations.
type GetAllOrganisationsParams struct {
	// Limit Size of the page, maximum is 100, default is 25
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page to return
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// AuthenticateLoginJSONRequestBody defines body for AuthenticateLogin for application/json ContentType.
type AuthenticateLoginJSONRequestBody = AuthenticateRequest

// CreateOrganisationJSONRequestBody defines body for CreateOrganisation for application/json ContentType.
type CreateOrganisationJSONRequestBody = OrganisationIn

// UserCreateJSONRequestBody defines body for UserCreate for application/json ContentType.
type UserCreateJSONRequestBody = UserIn
