// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthenticatePostRequest Authenticate
type AuthenticatePostRequest struct {
	Password string `json:"password" validate:"required,min=6,max=256"`
	Username string `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// AuthenticateToken Authenticate
type AuthenticateToken struct {
	Token string `json:"token" validate:"required"`
}

// Error Default error response
type Error struct {
	Message string `json:"message"`
}

// MetricsGetResponse Metrics for Prometheus response
type MetricsGetResponse = string

// Organisation Return of the Organisation object
type Organisation struct {
	Admins      []string  `json:"admins"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description" validate:"required,min=1,max=256"`
	Enabled     bool      `json:"enabled"`
	Fqdn        string    `json:"fqdn"`
	Id          string    `json:"id,omitempty"`
	Name        string    `json:"name" validate:"required,min=6,max=64,alphanum"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// OrganisationIn Creating the Organisation object
type OrganisationIn struct {
	Admins      []string `json:"admins"`
	Description string   `json:"description" validate:"required,min=1,max=256"`
	Enabled     bool     `json:"enabled"`
	Fqdn        string   `json:"fqdn" validate:"required,fqdn"`
	Name        string   `json:"name" validate:"required,min=6,max=64,alphanum"`
}

// Organisations Overview of all organisations
type Organisations = []Organisation

// UserIn Object to create the User
type UserIn struct {
	Enabled  bool   `json:"enabled"`
	OrgId    string `json:"org_id" validate:"required"`
	Password string `json:"password" validate:"required,min=6,max=256"`
	Role     string `json:"role,omitempty"`
	Username string `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// UserNoPassword Return of the User object
type UserNoPassword struct {
	CreatedAt time.Time `json:"created_at"`
	Enabled   bool      `json:"enabled"`
	Id        string    `json:"id" validate:"required"`
	OrgId     string    `json:"org_id" validate:"required"`
	Role      string    `json:"role"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username" validate:"required,min=6,max=64,alphanum"`
}

// GetAllOrganisationsParams defines parameters for GetAllOrganisations.
type GetAllOrganisationsParams struct {
	// Limit Size of the page, maximum is 100, default is 25
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page to return
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// AuthenticateLoginJSONRequestBody defines body for AuthenticateLogin for application/json ContentType.
type AuthenticateLoginJSONRequestBody = AuthenticatePostRequest

// CreateOrganisationJSONRequestBody defines body for CreateOrganisation for application/json ContentType.
type CreateOrganisationJSONRequestBody = OrganisationIn

// UserCreateJSONRequestBody defines body for UserCreate for application/json ContentType.
type UserCreateJSONRequestBody = UserIn

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate
	// (POST /v1/auth/login)
	AuthenticateLogin(c *gin.Context)
	// Health
	// (GET /v1/health)
	GetHealth(c *gin.Context)
	// Metrics
	// (GET /v1/metrics)
	GetMetrics(c *gin.Context)
	// Create an organisation
	// (POST /v1/organisation)
	CreateOrganisation(c *gin.Context)
	// Returns all organisations
	// (GET /v1/organisations)
	GetAllOrganisations(c *gin.Context, params GetAllOrganisationsParams)
	// Create User Account
	// (POST /v1/user)
	UserCreate(c *gin.Context)
	// Get all users
	// (GET /v1/user/{user})
	GetUserByID(c *gin.Context, user string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AuthenticateLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthenticateLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthenticateLogin(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMetrics(c)
}

// CreateOrganisation operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganisation(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrganisation(c)
}

// GetAllOrganisations operation middleware
func (siw *ServerInterfaceWrapper) GetAllOrganisations(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllOrganisationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllOrganisations(c, params)
}

// UserCreate operation middleware
func (siw *ServerInterfaceWrapper) UserCreate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin", "write", "readonly"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UserCreate(c)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameterWithOptions("simple", "user", c.Param("user"), &user, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin", "write", "readonly"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserByID(c, user)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/auth/login", wrapper.AuthenticateLogin)
	router.GET(options.BaseURL+"/v1/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/v1/metrics", wrapper.GetMetrics)
	router.POST(options.BaseURL+"/v1/organisation", wrapper.CreateOrganisation)
	router.GET(options.BaseURL+"/v1/organisations", wrapper.GetAllOrganisations)
	router.POST(options.BaseURL+"/v1/user", wrapper.UserCreate)
	router.GET(options.BaseURL+"/v1/user/:user", wrapper.GetUserByID)
}

type AuthenticateLoginRequestObject struct {
	Body *AuthenticateLoginJSONRequestBody
}

type AuthenticateLoginResponseObject interface {
	VisitAuthenticateLoginResponse(w http.ResponseWriter) error
}

type AuthenticateLogin200JSONResponse AuthenticateToken

func (response AuthenticateLogin200JSONResponse) VisitAuthenticateLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthenticateLogin403JSONResponse Error

func (response AuthenticateLogin403JSONResponse) VisitAuthenticateLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse MetricsGetResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth503JSONResponse Error

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200Response struct {
}

func (response GetMetrics200Response) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CreateOrganisationRequestObject struct {
	Body *CreateOrganisationJSONRequestBody
}

type CreateOrganisationResponseObject interface {
	VisitCreateOrganisationResponse(w http.ResponseWriter) error
}

type CreateOrganisation201JSONResponse Organisation

func (response CreateOrganisation201JSONResponse) VisitCreateOrganisationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganisation403JSONResponse Error

func (response CreateOrganisation403JSONResponse) VisitCreateOrganisationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganisation409JSONResponse string

func (response CreateOrganisation409JSONResponse) VisitCreateOrganisationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganisationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateOrganisationdefaultJSONResponse) VisitCreateOrganisationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetAllOrganisationsRequestObject struct {
	Params GetAllOrganisationsParams
}

type GetAllOrganisationsResponseObject interface {
	VisitGetAllOrganisationsResponse(w http.ResponseWriter) error
}

type GetAllOrganisations200ResponseHeaders struct {
	XNEXT     string
	XPREVIOUS string
}

type GetAllOrganisations200JSONResponse struct {
	Body    Organisations
	Headers GetAllOrganisations200ResponseHeaders
}

func (response GetAllOrganisations200JSONResponse) VisitGetAllOrganisationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-NEXT", fmt.Sprint(response.Headers.XNEXT))
	w.Header().Set("X-PREVIOUS", fmt.Sprint(response.Headers.XPREVIOUS))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetAllOrganisations403JSONResponse Error

func (response GetAllOrganisations403JSONResponse) VisitGetAllOrganisationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAllOrganisationsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAllOrganisationsdefaultJSONResponse) VisitGetAllOrganisationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UserCreateRequestObject struct {
	Body *UserCreateJSONRequestBody
}

type UserCreateResponseObject interface {
	VisitUserCreateResponse(w http.ResponseWriter) error
}

type UserCreate201JSONResponse struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Enabled   *bool      `json:"enabled,omitempty"`
	Id        *string    `json:"id,omitempty"`
	OrgId     *string    `json:"org_id,omitempty"`
	Role      *string    `json:"role,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Username  *string    `json:"username,omitempty"`
}

func (response UserCreate201JSONResponse) VisitUserCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UserCreate403JSONResponse Error

func (response UserCreate403JSONResponse) VisitUserCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UserCreate409JSONResponse string

func (response UserCreate409JSONResponse) VisitUserCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetUserByIDRequestObject struct {
	User string `json:"user"`
}

type GetUserByIDResponseObject interface {
	VisitGetUserByIDResponse(w http.ResponseWriter) error
}

type GetUserByID200JSONResponse UserNoPassword

func (response GetUserByID200JSONResponse) VisitGetUserByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserByID403JSONResponse Error

func (response GetUserByID403JSONResponse) VisitGetUserByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetUserByID404JSONResponse string

func (response GetUserByID404JSONResponse) VisitGetUserByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate
	// (POST /v1/auth/login)
	AuthenticateLogin(ctx context.Context, request AuthenticateLoginRequestObject) (AuthenticateLoginResponseObject, error)
	// Health
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Metrics
	// (GET /v1/metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Create an organisation
	// (POST /v1/organisation)
	CreateOrganisation(ctx context.Context, request CreateOrganisationRequestObject) (CreateOrganisationResponseObject, error)
	// Returns all organisations
	// (GET /v1/organisations)
	GetAllOrganisations(ctx context.Context, request GetAllOrganisationsRequestObject) (GetAllOrganisationsResponseObject, error)
	// Create User Account
	// (POST /v1/user)
	UserCreate(ctx context.Context, request UserCreateRequestObject) (UserCreateResponseObject, error)
	// Get all users
	// (GET /v1/user/{user})
	GetUserByID(ctx context.Context, request GetUserByIDRequestObject) (GetUserByIDResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AuthenticateLogin operation middleware
func (sh *strictHandler) AuthenticateLogin(ctx *gin.Context) {
	var request AuthenticateLoginRequestObject

	var body AuthenticateLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthenticateLogin(ctx, request.(AuthenticateLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthenticateLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AuthenticateLoginResponseObject); ok {
		if err := validResponse.VisitAuthenticateLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(ctx *gin.Context) {
	var request GetMetricsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganisation operation middleware
func (sh *strictHandler) CreateOrganisation(ctx *gin.Context) {
	var request CreateOrganisationRequestObject

	var body CreateOrganisationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganisation(ctx, request.(CreateOrganisationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganisation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateOrganisationResponseObject); ok {
		if err := validResponse.VisitCreateOrganisationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllOrganisations operation middleware
func (sh *strictHandler) GetAllOrganisations(ctx *gin.Context, params GetAllOrganisationsParams) {
	var request GetAllOrganisationsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllOrganisations(ctx, request.(GetAllOrganisationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllOrganisations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllOrganisationsResponseObject); ok {
		if err := validResponse.VisitGetAllOrganisationsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserCreate operation middleware
func (sh *strictHandler) UserCreate(ctx *gin.Context) {
	var request UserCreateRequestObject

	var body UserCreateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UserCreate(ctx, request.(UserCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UserCreateResponseObject); ok {
		if err := validResponse.VisitUserCreateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserByID operation middleware
func (sh *strictHandler) GetUserByID(ctx *gin.Context, user string) {
	var request GetUserByIDRequestObject

	request.User = user

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserByID(ctx, request.(GetUserByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUserByIDResponseObject); ok {
		if err := validResponse.VisitGetUserByIDResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbuBH+KyjamftCS6Kc5C6aydzk7VJ3mjiN7SZT13MDkysJNgkwACiZyei/dxYg",
	"xTfIkmP5mvYuH2JRXAL7+mD3ob7SSKaZFCCMppOvVEdzSJn9+Dw3cxCGR8zAe6nNB/icgzZ4KwYdKZ4Z",
	"LgWdtARpQDMlM1CGg10lY1ovpYrxM9ywNEuATupvAzqVKmWm/Z0pMpTSRnExowG9OZAs4weRjGEG4gBu",
	"jGIHhs3sDguW8Bi3nlAFn3OuIA5SLp49CVJ282z8+AldrQKaa1CCpdDWo/o23O+mTx4FLMnmTOQpXeHu",
	"lQydnNeaBLXJF+vt5eUVRIaugpZbT+U1iDt63lTP1OamxYA1HokHTub+tvetdCv77HqtlFR9W17BlOWJ",
	"IYC3iQKdSaHRqrX6X2kKWrMZLvdclIIyinJlNejavxZueqD/XNf4riHVMj5T3oJRPNJvwHyo9O3ZVcqQ",
	"qVTkvZIpmDnk2msgPRPXQi77AVkF9FjNmOCauVW7m3wAkytB5JSYOZCmLCm17XqHxSkXuuWc81Y5VJ/H",
	"aDk3kLqk6upVfsGUYgVeRwows35lpu348Wj86CAcHYwPT8PDySichKN/NasfE+rAcFsWvU1axjZXfVXf",
	"qIxHPGOi2FdBhy0UAcEuE4hdAGy+0smUJRoaUTQqh/Xml1ImwAQaMf0cd7T/5R+v3lVqg1hwJUUKwvg8",
	"wDsAyuPqQdlMDK/RKUYvM4VTbRXQPg6+Yyk8kAN9iBjQPIt3TJNw1zTp1C3H0i5xtpk/dRBbydpSqQxW",
	"UFWJr/abRXbkKcmXuDYXs/96Rf7Oi+cbVLebrb6HQunk9JZ0vlvS6n7OHi9ALTgs0UKWJC1s0bSRdH9R",
	"MKUT+udh3T0Oy9Zx2DqpVgFN2c2Rey4cjfrpeaZB+ern2CpNjCSuSq3LUbhXOPfJK6lmv3axVfJ4Py1R",
	"sL37fYBOV8kEWr6gClgsRVK0eg2bJTseGN9P81zGK/B20c1asF7wlQCm0Dv5vhGY21oplN4E2A/S6twn",
	"mbuJ/NOP4fjHp7M8vBzvK6EfuF6q3N2Wpg/TQXyXid7N9l26lw3JvwqohihX3BQnCNYujV8AU6BwlMSr",
	"S3v1S+Wtv308Reclcul6lNzMpeJfLLi/lDE4zkBmjRYGpyz8S1gUgdbeg2SNSFhvLD7Az0Q5gkETfLbb",
	"1y4Vt358AQTtb5wLUhFnPM5UMlcR+FawDrZHlC0aa2UdzrkxmRPhYir7oPAGQBAeAwREyBmRC1BEsBjE",
	"NQiyBDDkCn6mAU14BOUU6NKIvj06tU0ZNzaVPoISFkHIK351DSplQoC5yudzGtAFKO32CwejwcieTxkI",
	"lnE6oYeD0eDQop2ZW2cPF+EQ4zFM5IzbAzST2+gZoiVZAomYIDMwhBE7phMmYhJLok0+nVK7qXJ9bdx5",
	"/u92K5epoM0LGRcWCaUw2HthCmRZgqJciuGV7rScTToIrS1OIFJg/tTM8AlNi7PqoooZ29Z0bCKrbExv",
	"JU3qoisPu2oyt04ej0Z3M7BkXWhaDK6WZlDd+SZDHOvjMeH1TQaRgXjNImA5MGLhpioj3PLR6PBu2tcE",
	"y5Fwq1VxGVaRw7b3kot1e7ebWY708ZhyJnSOODHNk4Q0yCkcSpixfYgDrjxNmSr68XNYe978Gle+wIew",
	"RObAEgdtMzCbjnttD3snWh39DVf1auINmL+6db8pX3bzmYdd8jjQ6lEQxC3E7DIqj+8TeYMhT4gGhTgH",
	"LnT3jvR63RO3biXYjO3aqVVUTwptIK2jmTqfbA0nHjqVrCd4b9e3fNHbhcDrKF4vuElz2SHw/GD90p1p",
	"THTPv7YJTuy4LXI3UN4tmh2WwxPWFrWBMBTHO6Bq+CAa+vQ7sfCC+OIahpLt6Hr4fmjZxKS4PFS5JpUX",
	"Bnsonza+9fcIiDRzUEuugcQgOMRlA+ZMe3o301zRT2icOzHoeas2p26UN0j3qbrbs4gl2B8WBG64O8fW",
	"k9Cecmajkz/OQVR95ZTxRLeaZjo5b7fL52XHe7G6aILBxiKusKGVs16E2A3hum11D+eeJ8lxRyZjiqVg",
	"QGlrTqdY+Jc1vZWxGQQkZTc8zVPMtHA0CkgZCrweP8bxBB/7nIMqKrp1QhOechxD6mCsAzh+3Jhj8WI9",
	"l3FhDnFMLTdss0VcGJiBPS26Kp+WqiL2KOubDVqhkF+psKGT3XWzUk/tP49eF/dtHDvRP68J4VtY4CYF",
	"0Zh8ScU70KDnLa4xdkwQlrIvXMwaNOaae3AEg+Nc6XK5HKTFXGoziGTqJtIJ/Snk4bx2blrUyzQnc49S",
	"IV1d7AyH7ez1waINfmxHstuoyzmw2Ob8V/rp4N3rT6eeQYkkXFxjHmH6C7gxLrHklNShbVJoODVOhsNE",
	"RixB/wxZxnuF/DOu8Wz873w0Gj/R/As8s3VTm99/jfHp4P2H1/88Oj472aZkpmDBZa73p2i4u6Kr/+8z",
	"8zc7dHIB1TwHdU98xzPntmPh9mMHAWV7Q+qYUBZFMrcvWdpHDd50kg/Uh5ZvCTzeWyuYu3cD++g8G/m6",
	"A8J2YNPBY4t6rVhTGoZXTBez/HJesXQ1w7kVNjskSe4lSX5binqvlPQd6OX/Qap4tbp1OEmKsu90lMsf",
	"88i2eaSCoq2jSI1ZW6cQh3Ht6WMXLK7o6Qax7R8J7AbPa4VKYLavNVuAPPyK/682TgFvwFioRylNLnPb",
	"kDMS52laWKZCyKVvIMCdXhRHr7YNAlZRK2Zb6YyZRrPnRdrbOoWLB2TJOu/zPFFFX2Gz9Luoq0ffVlfo",
	"GxJL0ERIUw/evsryie5aW43F91NXrTrwVJTdRS2qJM9V4muHFziTrB/utdxJ0v4Bj4IE4x8Q+9oKq+0H",
	"q+8PFdboulY6v4bY8eVMLF2U169kytU6JLdnvdIXlY6ERbYLDMrTBQf4BCw5EROI7Zhern3mysP3mxD0",
	"8JA4RnO9Mog4k1wYx4wm/BpIKgU3snwzWi5b8qCri9V/AgAA//9hUWYAbCwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
