name: Test Go

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22', '1.23' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install OAPI-CodeGen
        run: go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen

      - name: Generate model structs
        run: go generate internal/core/domain/model/model-generator.go

      - name: Generate model structs (2)
        run: go generate internal/core/port/in/in-generator.go

      - name: Generate Server related functions
        run: go generate internal/adapter/in/http/api/server-generator.go

      - name: Do a go mod edit to specific golang version
        run: go mod edit -go ${{ matrix.go-version }}

      - name: Do a go mod tidy
        run: go mod tidy

      - name: Test with Go
        run: go test ./... -json > TestResults-${{ matrix.go-version }}.json

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude-generated -fmt json ./... > TestResults-gosec-${{ matrix.go-version }}.json'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: dj-wasabi/api:${{ matrix.go-version }}

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json

      - name: Upload Gosec test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-gosec-${{ matrix.go-version }}
          path: TestResults-gosec-${{ matrix.go-version }}.json

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Build Application
        run: go build -o ./api ./cmd/api
